name: tb-attseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - tqdm
  - biopython
  - fastp
  - multiqc
  - nextflow
  - samtools=1.17
  - bwa=0.7.17
  - htseq=2.0.5
